<?xml version='1.0'?>
<package format='2'>
  <name>hpp_tutorial</name>
  <version>8.0.0</version>
  <description>
    Tutorial for Humanoid path planner platform
  </description>
  <author>Florent Lamiraux</author>
  <maintainer email="hpp@laas.fr">Florent Lamiraux</maintainer>
  <license>BSD 2-Clause</license>
  <build_depend>hpp-manipulation</build_depend>
  <build_depend>hpp-gepetto-viewer</build_depend>
  <exec_depend>example-robot-data</exec_depend>
</package>
